name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Triggers the workflow on a push to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest  # Runs the job on a Linux machine

    steps:
      # Step 1: Check out your repository code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}  # GitHub automatically generates this token
          publish_dir: . # Replace './public' with your output folder
